In [7]:
import numpy as np
import csv

In [4]:
data_ndarray = np.array([10,20,30])

In [6]:
type(data_ndarray)

numpy.ndarray

In [15]:
# import nyc_taxi.csv as a list of lists
dataset_loc = 'D:/Dataquest/Dataquest 2022 Learning/Datasets/'
f = open( dataset_loc + 'nyc_taxis.csv','r')
taxi_list = list(csv.reader(f))


In [14]:
#remove the header row
taxi_list = taxi_list[1:]

#convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)


In [16]:
# convert list of lists to 2-dimensional array using numpy.array()
taxi = np.array(converted_taxi_list)


In [24]:
# let's practice selecting one row, multiple rows and single items from our taxi ndarray
print(f'the first row of ndarray {taxi[0]}')
print(f'from row 391 to row 500 of ndarray {taxi[391:501]}')
print(f'select a single element at row 21 and column 5 {taxi[21,5]}')

the first row of ndarray [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
 1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
 1.000e+00]
from row 391 to row 500 of ndarray [[2.016e+03 1.000e+00 2.000e+00 ... 3.000e+00 3.030e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 6.670e+00 4.001e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 1.167e+01 7.001e+01 1.000e+00]
 ...
 [2.016e+03 1.000e+00 4.000e+00 ... 3.090e+00 1.339e+01 1.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 4.000e+00 2.680e+01 1.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 7.050e+00 4.239e+01 1.000e+00]]
select a single element at row 21 and column 5 2.0


In [26]:
# use vector addition to add fare_amount and fees_amount. Assign the result to fare_and_fees.
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees = fare_amount + fees_amount
print(f'first 5 rows of fare_amount {fare_amount[:6]}')
print(f'first 5 rows of fees_amount {fees_amount[:6]}')
print(f'first 5 rows of fare_and_fees {fare_and_fees[:6]}')

first 5 rows of fare_amount [45.  36.5 26.  17.5 52.  24.5]
first 5 rows of fees_amount [1.3 1.3 1.3 1.3 0.8 1.3]
first 5 rows of fare_and_fees [46.3 37.8 27.3 18.8 52.8 25.8]


In [27]:
# use vector division to divide trip_distance_miles by trip_length_hours. Assign the result to trip_mph.
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour
trip_mph=trip_distance_miles/trip_length_hours

print(f'first 5 rows of trip_distance_miles{trip_distance_miles[:6]}')
print(f'first 5 rows of trip_length_hours {trip_length_hours[:6]}')
print(f'first 5 rows of trip_mph {trip_mph[:6]}')

first 5 rows of trip_distance_miles[16.29 12.7   8.7   5.56 21.45  8.45]
first 5 rows of trip_length_hours [0.42222222 0.40611111 0.33611111 0.21083333 0.55666667 0.2575    ]
first 5 rows of trip_mph [38.58157895 31.27222982 25.88429752 26.3715415  38.53293413 32.81553398]


### NumPy ndarrays have methods for many different calculations. Here are a few of the key methods:
- ndarray.min() to calculate the minimum value
- ndarray.max() to calculate the maximum value
- ndarray.mean() to calculate the mean or average value
- ndarray.sum() to calculate the sum of the values

In [30]:
print(f'maximum value of trip_mph is {trip_mph.max()}')
print(f'minimumvalue of trip_mph is {trip_mph.min()}')
print(f'average of trip_mph is {trip_mph.mean()}')

maximum value of trip_mph is 82800.0
minimumvalue of trip_mph is 0.0
average of trip_mph is 170.04918947908376


###  If we use the ndarray.max() method on a 2D ndarray without any additional parameters, it will return a single value, just like a 1D array

![This is a image](https://raw.githubusercontent.com/tongNJ/Dataquest-Online-Courses-2022/main/Pictures/numpy-pic-1.PNG)